### ISSUE TITLE
Add a parameter for state file location

### ISSUE THREAD

**Issue by eshepelyuk** [hundredwatt/tuki#2]
It would be great if the state location could be configured to a local file or different git repository.

The scenario is when there's a single repository of scripts but those scripts can be run against multiple environmets and not simultaneously. I.e. run in dev stage prod only after testing.
In this case multiple state file location would be beneficial.

If generalizing further, it also would be great to have other sources of scripts, like local folder.

**Comment by hundredwatt** [comment]
There is an undocumented env variable `STATE_FILE` that controls its location. 

For multiple environments, you could set up a repo like this:

```
staging/
  * .tuki/state.jsonl
  * script1.sh
  * ...
production/
  * .tuki/state.jsonl
  * script1.sh
  * ...
```

Then run multiple instances of Tuki with:

 * Staging: `STATE_FILE="staging/.tuki/state.jsonl" SCRIPTS_DIR="staging/" ./tuki`
 * Production: `STATE_FILE="production/.tuki/state.jsonl" SCRIPTS_DIR="production/" ./tuki`
 
 
We could definitely add easier configuration for multiple environments, but this approach would work currently (just need to document the STATE_FILE env var).

> If generalizing further, it also would be great to have other sources of scripts, like local folder.

Can you please expand on what you are thinking here?

**Comment by eshepelyuk** [comment]
thanks for explaining about state file location.
